#pragma config(Sensor, dgtl1,  Shift,          sensorDigitalOut)
#pragma config(Motor,  port2,           FRBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FLBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BRBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BLBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LTrans,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RTrans,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LLift,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RLift,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool trans;
	while(true)
	{
		if(trans == false)
		{
			vexRT[Ch3] = motor[LTrans];
			vexRT[Ch3] = motor[FLBase];
			vexRT[Ch3] = motor[BLBase];
	 		vexRT[Ch2] = motor[RTrans];
	 		vexRT[Ch2] = motor[FRBase];
	 		vexRT[Ch2] = motor[BRBase];
	 		if(vexRT[Btn5U] == 1)
	 		{
	 			motor[LLift] = 100;
	 			motor[RLift] = 100;
	 		}
	 		if(vexRT[Btn5D] == 1)
	 		{
	 			motor[LLift] = -100;
	 			motor[RLift] = -100;
	 		}
	 		if(vexRT[Btn8U] == 1)
	 		{
	 			trans = true;
	 			SensorValue[shift] = 1;
	 			wait10Msec(100);
	 		}
		}
		if(trans == true)
		{
			vexRT[Ch3] = motor[FLBase];
			vexRT[Ch3] = motor[BLBase];
	 		vexRT[Ch2] = motor[FRBase];
	 		vexRT[Ch2] = motor[BRBase];
	 		if(vexRT[Btn5U] == 1)
	 		{
	 			motor[LLift] = 100;
	 			motor[RLift] = 100;
	 			motor[LTrans] = 100;
	 			motor[RTrans] = 100;
	 		}
	 		if(vexRT[Btn5D] == 1)
	 		{
	 			motor[LLift] = -100;
	 			motor[RLift] = -100;
	 			motor[LTrans] = -100;
	 			motor[RTrans] = -100;
	 		}
	 		if(vexRT[Btn8U] == 1)
	 		{
	 			trans = false;
	 			SensorValue[shift] = 0;
	 			wait10Msec(100);
	 		}
		}
	}


}
