#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left = 1;
int select = 2;
int right = 4;
int reset = 7;
string mainScreen[3] = {"<- Autonomous ->", "<- Statistics ->", "<- Battery V. ->"};
string autonScreen[8] = {/*each auton*/};
string statScreen[3] = { /*base*/, /*lift*/, /*intake*/ };
string batteryLife[2] = { /*Primary*/, /*Backup*/ };


void clearAllLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
}

void displayScreen(const string display){
	displayLCDString(0,0, display)
	displayLCDCenteredString(1,"<Select>");
}

task main()
{
	bLCDBacklight = 1;
	int x = 0;
	int y = 0;
	int z = 0;
	while(true){
		clearAllLCD();
		if(y == 0){
			displayScreen(mainScreen[x]);
		}
		else if(y == 1){
			//second screen
		}

		if(nLCDButtons == left){
			x--;
		}
		else if(nLCDButtons == right){
			x++;
		}
		else if(nLCDButtons == select){
			y = 1;
			x = 0;
		}
		else if(nLCDButtons == reset){
			y = 0;
			x = 0;
		}

		if(x == -1){
			x = 2;
		}
		else if(x == 3){
			x = 0;
		}
		wait1Msec(125);
	}
}
