#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  Shift,          sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           LIntake,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FRBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRBase,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           BLBase,        tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           FLBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RTrans,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LTrans,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LLift,         tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           RLift,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RIntake,       tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

int total = 3588;
int cl = -4507 + 3588 + 3588;

void clear(){									//Clears all values and resets them to 0(Motors and Encoders)
	nMotorEncoder[BLBase] = 0;
	nMotorEncoder[BRBase] = 0;
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
	motor[RLift] = 0;
	motor[LLift] = 0;
	motor[LTrans] = 0;
 	motor[RTrans] = 0;
 	motor[LIntake] = 0;
	motor[RIntake] = 0;
}

void right(int speed){				//Power right side base motors
	motor[FRBase] = speed;
	motor[BRBase] = speed;
}

void left(int speed){					//Power left side base motors
	motor[FLBase] = speed;
	motor[BLBase] = speed;
}

void forward(int distance, int speed){		//Move Forward
	while(nMotorEncoder[BLBase] < distance && nMotorEncoder[BRBase] > -distance){
		right(speed);
		left(speed);
	}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}

void backward(int distance, int speed){		//Move Backwards
	while(nMotorEncoder[BLBase] > -distance && nMotorEncoder[BRBase] < distance){
			right(-speed);
			left(-speed);
		}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}

void turnRight(int distance, int speed){	//Turn Right
	while(nMotorEncoder[BLBase] < distance && nMotorEncoder[BRBase] < distance){
		right(-speed);
		left(speed);
	}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}

void turnLeft(int distance, int speed){		//Turn Left
	while(nMotorEncoder[BLBase] > -distance && nMotorEncoder[BRBase] > -distance){
		left(-speed);
		right(speed);
	}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}

void swingRight(int distance, int speed){	//Swing(One motor moves 1/2 speed of other) Right
	while(nMotorEncoder[BLBase] < distance){
		right(speed/2);
		left(speed);
	}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}


void swingLeft(int distance, int speed, ){//Swing(One motor moves 1/2 speed of other) Left
	while(nMotorEncoder[BRBase] > -distance){
		left(speed/2);
		right(speed);
	}
	motor[FRBase] = 0;
	motor[BRBase] = 0;
	motor[FLBase] = 0;
	motor[BLBase] = 0;
}

void lift(int height, int speed){					//Lift to a specific height
	while(height > nMotorEncoder[LLift])
	{
		motor[RLift] = speed;
		motor[LLift] = speed;
		motor[LTrans] = speed;
	 	motor[RTrans] = speed;
	}
	motor[RLift] = 0;
	motor[LLift] = 0;
	motor[LTrans] = 0;
 	motor[RTrans] = 0;
}

void down(int time, int speed){						//Retract lift downwards
	motor[RLift] = -speed;
	motor[LLift] = -speed;
	motor[LTrans] = -speed;
	motor[RTrans] = -speed;
	wait10Msec(time);
	motor[RLift] = 0;
	motor[LLift] = 0;
	motor[LTrans] = 0;
 	motor[RTrans] = 0;
}

void intake(int time, int speed){					//Intake/Outtake
	motor[LIntake] = speed;
	motor[RIntake] = speed;
	wait10Msec(time);
	motor[LIntake] = 0;
	motor[RIntake] = 0;
}

void transmission(){											//Change transmission mode
	if(SensorValue[Shift] == 0)
		SensorValue[Shift] = 1;
	else if(SensorValue[Shift] == 1)
		SensorValue[Shift] = 0;
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	nMotorEncoder[RIntake] = nMotorEncoder[RIntake] + 3588 + 3588;
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task reset()
{
	while(nMotorEncoder[RIntake]%total < p1%total)
	{
		motor[LIntake] = -127;
		motor[RIntake] = -127;
	}
	motor[LIntake] = 0;
	motor[RIntake] = 0;
}

task next()
{
	while(nMotorEncoder[RIntake] < nMotorEncoder[RIntake] + 700)
	{
		motor[LIntake] = 127;
		motor[RIntake] = 127;
	}
	motor[LIntake] = 0;
	motor[RIntake] = 0;
}

task claw()
{
	while(nMotorEncoder[RIntake]%total < cl%total)
	{
		motor[LIntake] = -127;
		motor[RIntake] = -127;
	}
	motor[LIntake] = 0;
	motor[RIntake] = 0;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//Setup Phase
	clear();
	nMotorEncoder[LLift] = 0;
	lift(350, 127);
	down(70, 70);
	lift(150, 127);
	intake(100, -127);
	//down(10, 60);
	clear();

	//Move Towards Cube and Intake Cube
	forward(220, 50);
  clear();
  intake(120, 127);

  //Setup Approach Angle for Outtaking Cube
  turnLeft(50, 70);
  Sleep(50);
  forward(500, 70);
  clear();
  Sleep(50);

  //Lift and Intake so that Cubes are in Tray and in a Position Ready to Outtake
  lift(1380, 80);
  intake(40, 127);
  Sleep(60);
  clear();

  //Set up Outtaking Angle and Position
  turnRight(340 ,70);
  clear();
  Sleep(100);
  forward(120, 50);
  clear();
  swingRight(50, 50);
  clear();

  //Outtake Cubes
  intake(350, -127);

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	int lift = 0;											//1
	int cube = 74;
	int small = 700;
	int medium = 1480;
	int large = 1230;
	int intakerise = 450;
	SensorValue[Shift] = 0;						//Pnuematic Default Position
	while(true)
	{
		if(SensorValue[Shift] == 1)			//6 Motor Drive Mode
		{
			motor[LTrans] = vexRT[Ch3];
			motor[FLBase] = vexRT[Ch3];
			motor[BLBase] = vexRT[Ch3];
	 		motor[RTrans] = vexRT[Ch2];
	 		motor[FRBase] = vexRT[Ch2];
	 		motor[BRBase] = vexRT[Ch2];
	 		if(vexRT[Btn5U] == 1)					//Lift Up
	 		{
	 			if(lift == 0)
	 			{
	 				if(nMotorEncoder[LLift] < cube)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 				}
	 			}
	 			else if(lift == 1)
	 			{
	 				if(nMotorEncoder[LLift] < small)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 				}
	 			}
	 			else if(lift == 2)
	 			{
	 				if(nMotorEncoder[LLift] < medium)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 				}
	 			}
	 			else if(lift == 3)
	 			{
	 				if(nMotorEncoder[LLift] < large)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 				}
	 			}
	 		}
	 		else if(vexRT[Btn7U] == 1)
	 		{
	 				if(nMotorEncoder[LLift] < intakerise)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 0;
	 					motor[RLift] = 0;
	 				}
	 		}
	 		else if(vexRT[Btn5D] == 1)		//Retract Lift Down
	 		{
	 			motor[LLift] = -127;
	 			motor[RLift] = -127;
	 		}
	 		else
	 		{
	 			motor[LLift] = 0;
	 			motor[RLift] = 0;
	 		}
	 		if(vexRT[Btn8U] == 1)					//Shift to 4 Motor Base
	 		{
	 			SensorValue[Shift] = 0;
	 			wait10Msec(50);
	 		}

		}																//4 Motor Base Mode
		if(SensorValue[Shift] == 0)
		{
			motor[FLBase] = vexRT[Ch3];
			motor[BLBase] = vexRT[Ch3];
	 		motor[FRBase] = vexRT[Ch2];
	 		motor[BRBase] = vexRT[Ch2];
	 		if(vexRT[Btn5U] == 1)					//Lift Up
	 		{
	 			if(lift == 0)
	 			{
	 				if(nMotorEncoder[LLift] < cube)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 					motor[LTrans] = 127;
	 					motor[RTrans] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 					motor[LTrans] = 10;
	 					motor[RTrans] = 10;
	 				}
	 			}
	 			else if(lift == 1)
	 			{
	 				if(nMotorEncoder[LLift] < small)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 					motor[LTrans] = 127;
	 					motor[RTrans] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 					motor[LTrans] = 10;
	 					motor[RTrans] = 10;
	 				}
	 			}
	 			else if(lift == 2)
	 			{
	 				if(nMotorEncoder[LLift] < medium)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 					motor[LTrans] = 127;
	 					motor[RTrans] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 					motor[LTrans] = 10;
	 					motor[RTrans] = 10;
	 				}
	 			}
	 			else if(lift == 3)
	 			{
	 				if(nMotorEncoder[LLift] < large)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 					motor[LTrans] = 127;
	 					motor[RTrans] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 					motor[LTrans] = 10;
	 					motor[RTrans] = 10;
	 				}
	 			}
	 		}
	 		else if(vexRT[Btn7U] == 1)
			{
	 				if(nMotorEncoder[LLift] < intakerise)
	 				{
	 					motor[LLift] = 127;
	 					motor[RLift] = 127;
	 					motor[LTrans] = 127;
	 					motor[RTrans] = 127;
	 				}
	 				else
	 				{
	 					motor[LLift] = 10;
	 					motor[RLift] = 10;
	 					motor[LTrans] = 10;
	 					motor[RTrans] = 10;
	 				}

	 		}
	 		else if(vexRT[Btn5D] == 1)			//Retract Lift Downwards
	 		{
	 			motor[LLift] = -127;
	 			motor[RLift] = -127;
	 			motor[LTrans] = -127;
	 			motor[RTrans] = -127;
	 		}
	 		else
	 		{
	 			motor[LLift] = 0;
	 			motor[RLift] = 0;
	 			motor[LTrans] = 0;
	 			motor[RTrans] = 0;
	 		}
	 		if(vexRT[Btn8U] == 1)						//Shift to 6 Motor Drive
	 		{
	 			SensorValue[Shift] = 1;
	 			wait10Msec(50);
	 		}
		}
		if(vexRT[Btn6U] == 1)							//Intake
		{
			motor[LIntake] = 127;
			motor[RIntake] = 127;
		}
		else if(vexRT[Btn6D] == 1)				//Outtake
		{
			motor[LIntake] = -127;
			motor[RIntake] = -127;
		}
		else
		{
			motor[LIntake] = 0;
			motor[RIntake] = 0;
		}
		if(vexRT[Btn8DXmtr2] == 1)
		{
			lift = 0;
		}
		if(vexRT[Btn8LXmtr2] == 1)
		{
			lift = 1;
		}
		if(vexRT[Btn8UXmtr2] == 1)
		{
			lift = 2;
		}
		if(vexRT[Btn8RXmtr2] == 1)
		{
			lift = 3;
		}
		if(vexRT[Btn5DXmtr2] == 1)		//Reset
		{
			startTask(reset);
		}
		if(vexRT[Btn5UXmtr2] == 1)		//Next
		{
			startTask(next);
		}
		if(vexRT[Btn6UXmtr2] == 1)		//Claw
		{
			startTask(claw);
		}
		if(vexRT[Btn7L] == 1)
		{
			startTask(autonomous);
			stopTask(usercontrol);
		}
	}
}
