#pragma config(Motor,  port1,            ,             tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <FlashLib.h>

static char robotData[6000];
task main()
{
    int x = 0;
    int y = 0;
    int z;
    unsigned char *data;
    int datalength;
    string temp;

    RCFS_ReadVTOC();

    if( RCFS_GetFile( "rerunData", &data, &datalength ) == RCFS_SUCCESS )
    {
      while(x < datalength){
      	if(*(data+x) != 32){
      		robotData[y] = *(data+x);
      		y++;
      	}
      	x++;
      }
    }

    for(z=0;z<6000;z+= 4){
    	if(robotData[z] == 49){
        motor[port1] = 127;
     	}
     	else if(robotData[z] = 48){
     		motor[port1] = 0;
    	}

    	if(robotData[z+1] == 49){
        motor[port2] = 127;
     	}
     	else if(robotData[z+1] = 48){
     		motor[port2] = 0;
    	}

    	if(robotData[z+2] == 49){
        motor[port3] = 127;
     	}
     	else if(robotData[z+2] = 48){
     		motor[port3] = 0;
    	}

    	if(robotData[z+3] == 49){
        motor[port10] = 127;
     	}
     	else if(robotData[z+3] = 48){
     		motor[port10] = 0;
    	}
      wait1Msec(10);
    }
}
