#pragma config(Motor,  port1,            ,             tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <FlashLib.h>

task main()
{
    int x = 0;
    unsigned char *data;
    int datalength;
    string temp;

    RCFS_ReadVTOC();

    if( RCFS_GetFile( "rerunData", &data, &datalength ) == RCFS_SUCCESS )
    {
      for(i=0;i<14988;i+= 6){
        robotData[i] = vexRT[Ch3];
        robotData[i+1] = vexRT[Ch2];
        robotData[i+2] = vexRT[Btn5U];
        robotData[i+3] = vexRT[Btn5D];
        robotData[i+4] = vexRT[Btn6U];
        robotData[i+5] = vexRT[Btn6D];
        wait1Msec(6);
    	}
    }
}
