#pragma config(Motor,  port1,            ,             tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <FlashLib.h>

task main()
{
    int x = 0;
    unsigned char *data;
    int datalength;
    string temp;

    RCFS_ReadVTOC();

    if( RCFS_GetFile( "rerunData", &data, &datalength ) == RCFS_SUCCESS )
    {
      while(x < datalength){
      	motor[port1] = *(data+x);
      	x++;
      	wait10Msec(1);
      }
    }
}
