#pragma config(Motor,  port1,           LIntake,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FRBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BRBase,        tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           BLBase,        tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port5,           FLBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LLift,         tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port9,           RLift,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          RIntake,       tmotorVex393_HBridge, openLoop, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <FlashLib.h>

task main()
{
    int i = 0;
    unsigned char *data;
    int datalength;

    RCFS_ReadVTOC();

    if( RCFS_GetFile( "rerun", &data, &datalength ) == RCFS_SUCCESS )
    {
      while(i<datalength){
        motor[FLBase] = *(data+i);
        motor[BLBase] = *(data+i);
        motor[FRBase] = *(data+(i+1));
        motor[BRBase] = *(data+(i+1));
        if(*(data+(i+2))==1){
        	motor[LLift] = 127;
        	motor[RLift] = 127;
        }
        else if(*(data+(i+3))==1){
        	motor[LLift] = -127;
        	motor[RLift] = -127;
        }
        if(*(data+(i+4))==1){
        	motor[LIntake] = 127;
        	motor[RIntake] = 127;
        }
        else if(*(data+(i+5))==1){
        	motor[LIntake] = -127;
        	motor[RIntake] = -127;
        }
        i+=6;
        wait1Msec(6);
    	}
    }
}
