#pragma config(Motor,  port2,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,            ,             tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,            ,             tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include <FlashLib.h>

task main()
{
    int i = 0;
    unsigned char *data;
    int datalength;

    RCFS_ReadVTOC();

    if( RCFS_GetFile( "a", &data, &datalength ) == RCFS_SUCCESS )
    {
      while(i<datalength){
        motor[port2] = *(data+i);
        motor[port3] = *(data+(i+1));
        motor[port4] = *(data+(i+2));
        motor[port5] = *(data+(i+3));
        motor[port6] = *(data+(i+4));
        motor[port7] = *(data+(i+5));
        i+=6;
        wait1Msec(6);
    	}
    }
}
