#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void clearAllLCD(){
	clearLCDLine(0);
	clearLCDLine(1);
	wait10Msec(10);
}

void displayLCDStringSelect(int nLine, int nPos, string sString){
	displayLCDString(nLine, nPos, ">");
	displayLCDString(nLine, nPos+1, sString);
}

void autonConfirm(int nLine, int nPos, string auton){
	displayLCDString(nLine, nPos, auton);
	displayLCDString(nLine+1, nPos, "Confirm Auton?");
}

task main()
{
	bLCDBacklight = 1;
	//Created these variables because the displayLCDStringSelect function only takes unsigned strings
	string red = "Red";
	string blue = "Blue";
	string left = "Left";
	string right = "Right";
	string build = "Build";
	string score = "Score";
	string redLeftBuild = "Red Left Build";
	string blueLeftBuild = "Blue Left Build";
	string redRightBuild = "Red Right Build";
	string blueRightBuild = "Blue Right Build";
	string redLeftScore = "Red Left Score";
	string blueLeftScore = "Blue Left Score";
	string redRightScore = "Red Right Score";
	string blueRightScore = "Blue Right Score";
	bLCDBacklight = 1;
	while(true){
		if(nLCDButtons == 2){
			clearAllLCD();
			displayLCDStringSelect(0,0,red);
			displayLCDString(1,0,blue);
			if(nLCDButtons == 4){
				clearAllLCD();
				displayLCDStringSelect(0,0,left);
				displayLCDString(1,0,right);
				if(nLCDButtons == 4){
					clearAllLCD();
					displayLCDStringSelect(0,0,build);
					displayLCDString(1,0,score);
					if(nLCDButtons == 4){
						clearAllLCD();
						autonConfirm(0,0,redLeftBuild);
						if(nLCDButtons == 4){
							//Red Left Build Autonomous Code
						}
					}
					else if(nLCDButtons == 2){
						clearAllLCD();
						displayLCDString(0,0,build);
						displayLCDStringSelect(1,0,score);
						if(nLCDButtons == 4){
							clearAllLCD();
							autonConfirm(0,0,redLeftScore);
							if(nLCDButtons == 4){
								//Red Left Score Autonomous Code
							}
						}
					}
				}
				else if(nLCDButtons == 2){
					clearAllLCD();
					displayLCDString(0,0,left);
					displayLCDStringSelect(1,0,right);
					if(nLCDButtons == 4){
						clearAllLCD();
						displayLCDStringSelect(0,0,build);
						displayLCDString(1,0,score);
						if(nLCDButtons == 4){
							clearAllLCD();
							autonConfirm(0,0,redRightBuild);
							if(nLCDButtons == 4){
								//Red Right Build Autonomous Code
							}
						}
						else if(nLCDButtons == 2){
							clearAllLCD();
							displayLCDString(0,0,build);
							displayLCDStringSelect(1,0,score);
							if(nLCDButtons == 4){
								clearAllLCD();
								autonConfirm(0,0,redRightScore);
								if(nLCDButtons == 4){
									//Red Right Score Autonomous Code
								}
							}
						}
					}
				}
			}
			else if(nLCDButtons == 2){
				clearAllLCD();
				displayLCDString(0,0,red);
				displayLCDStringSelect(1,0,blue);
				if(nLCDButtons == 4){
					clearAllLCD();
					displayLCDStringSelect(0,0,left);
					displayLCDString(1,0,right);
					if(nLCDButtons == 4){
						clearAllLCD();
						displayLCDStringSelect(0,0,build);
						displayLCDString(1,0,score);
						if(nLCDButtons == 4){
							clearAllLCD();
							autonConfirm(0,0,blueLeftBuild);
							if(nLCDButtons == 4){
								//Blue Left Build Autonomous Code
							}
						}
						else if(nLCDButtons == 2){
							clearAllLCD();
							displayLCDString(0,0,build);
							displayLCDStringSelect(1,0,score);
							if(nLCDButtons == 4){
								clearAllLCD();
								autonConfirm(0,0,blueLeftScore);
								if(nLCDButtons == 4){
									//Blue Left Score Autonomous Code
								}
							}
						}
					}
					else if(nLCDButtons == 2){
						clearAllLCD();
						displayLCDString(0,0,left);
						displayLCDStringSelect(1,0,right);
						if(nLCDButtons == 4){
							clearAllLCD();
							displayLCDStringSelect(0,0,build);
							displayLCDString(1,0,score);
							if(nLCDButtons == 4){
								clearAllLCD();
								autonConfirm(0,0,blueRightBuild);
								if(nLCDButtons == 4){
									//Blue Right Build Autonomous Code
								}
							}
							else if(nLCDButtons == 2){
								clearAllLCD();
								displayLCDString(0,0,build);
								displayLCDStringSelect(1,0,score);
								if(nLCDButtons == 4){
									clearAllLCD();
									autonConfirm(0,0,blueRightScore);
									if(nLCDButtons == 4){
										//Blue Right Score Autonomous Code
									}
								}
							}
						}
					}
				}
			}
		}
	}
}
